<h1> Getting started with TensorFlow </h1>

In this notebook, you play around with the TensorFlow Python API. For more information have a look at [Tensorflow Documentation](https://www.tensorflow.org/programmers_guide/low_level_intro)

In this Notebook we are going through these steps:
- Multiply & add arrays using Numpy. 
- Create a Tensorflow graph and execute the graph. 
- Build Heron's Formula using Tensorflow.
- Use tf.eager. 
- Extra: work with Layers API. 

**Make sure that you run through this notebook from the beginning**

First let us import the TF and Numpy library. 

In [2]:
# Import Libraries
import tensorflow as tf
import numpy as np

# Let's print the TF version 
print (tf.__version__)

1.11.0


<h3> Tensor Values </h3>

As a reminder the different ranks for Tensor's

In [0]:
3. # a rank 0 tensor; a scalar with shape [],
[1., 2., 3.] # a rank 1 tensor; a vector with shape [3]
[[1., 2., 3.], [4., 5., 6.]] # a rank 2 tensor; a matrix with shape [2, 3]
[[[1., 2., 3.]], [[7., 8., 9.]]] # a rank 3 tensor with shape [2, 1, 3]

<h2> Adding two arrays using Numpy </h2>

First, let's try doing this using numpy, the Python numeric package. numpy code is immediately evaluated.

In [0]:
#Let's add two numpy arrays (tensors)

a = np.array([5, 3, 8])
b = np.array([3, -1, 2])
c = np.add(a, b)
print c

[ 8  2 10]


**Exercise 1:**

- *Now change the code and multiply the two arrays.* 
- *If you want you can also change the values of the arrays.*
- *You can also try other Numpy [operators](http://www.scipy-lectures.org/intro/numpy/operations.html)*

** Solution 1 **

In [0]:
#Let's multiply two numpy arrays (tensors)

a = np.array([5, 3, 8])
b = np.array([3, -1, 2])
c = np.multiply(a, b)
print c

[15 -3 16]


<h4> OR </h4>

In [0]:
# Shortcut for multiplying
c = a * b
print c

[15 -3 16]


We can do direct operations on the arrays. Do you also notice that when we apply the operation we can print the direct result. 

<h2> Tensorflow </h2>

The equivalent code in TensorFlow consists of two steps:
<p>
<h3> Step 1: Build a TF graph </h3>

In [4]:
a = tf.constant([5, 3, 8])
b = tf.constant([3, -1, 2])
c = tf.add(a, b)
print c

Tensor("Add_1:0", shape=(3,), dtype=int32)


**Exercise 2**

c is an operation ("Add") that returns a tensor of shape (3,) and holds data type int32. The shape is inferred from the computation graph.

*Try the following in the cell above:*
- *Change the 5 to 5.0, and similarly the other five numbers. What happens when you run this cell?*
- *Add an extra number to a, but leave b at the original (3,) shape. What happens when you run this cell?*
- *Change the code back to a version that works*
- *Run the graph*

**Extra Question**

- When is it possible to apply opperations on matrices with different shapes?

** Solution 2 **

ValueError: *Input 'y' of 'Add' Op has type int32 that does not match type float32 of argument 'x'.* 
<p> 
We need to make sure that the data types of our tensors match 
<p>
ValueError: *ValueError: Dimensions must be equal, but are 4 and 3 for 'Add_3' (op: 'Add') with input shapes: [4], [3].*
<p>
Also make sure that your Tensors have a shape we can multiply.

We have now seen that TF does lazy evaluation. It will print the information about the Tensor but not the result:

*Tensor("Add_7:0", shape=(3,), dtype=int32)*

In [0]:
# It works for tensors that have a different shape. 
a2 = tf.constant([5, 3])
b2 = tf.constant([3])
c2 = tf.add(a2, b2)
print c2

Tensor("Add_1:0", shape=(2,), dtype=int32)


**Exercise 3**

- *Now write the equivilant for the Numpy code with the multiply operator - your solution at exercise one - using Tensorflow. 
- *Add the tf.session code that will give you the results of running your graph. *
- *Check if you are getting the same results as with the Numpy operation?*

**Make sure that you give your variables a new name!**

** Solution 3a **

In [8]:
# Creating the graph Graph 

x = tf.constant([5, 3, 8])
y = tf.constant([3, -1, 2])
z = tf.multiply(x, y)
print z

Tensor("Mul_1:0", shape=(3,), dtype=int32)


In [9]:
#Sesstion to run the graph
# Launch the graph in a session.
sess = tf.Session()

# Evaluate the tensor.
print(sess.run(z))

[15 -3 16]


** Solution 3a **

In [0]:
_m = np.array([5, 3, 8])
_n = np.array([3, -1, 2])
_o = np.multiply(_m, _n)
m = tf.convert_to_tensor(_m)
n = tf.convert_to_tensor(_n)
o = tf.convert_to_tensor(_o)

In [11]:
#Sesstion to run the graph
# Launch the graph in a session.
sess = tf.Session()

# Evaluate the tensor.
print(sess.run(z))

[15 -3 16]


<h2> Heron's Formula in TensorFlow </h2>

The area of triangle whose three sides are $(a, b, c)$ is $\sqrt{s(s-a)(s-b)(s-c)}$ where $s=\frac{a+b+c}{2}$ 

Look up the available operations at https://www.tensorflow.org/api_docs/python/tf

**Exercise 4**

- *Now implement the Heron's Formula mentioned above.*

In [0]:
def compute_area(sides):
  # slice the input to get the sides
  
  # Heron's formula
  s =         # Function for S here. 
  areasq =    # Area squared here
  return tf.sqrt(areasq)

with tf.Session() as sess:
  # pass in two triangles
  area = compute_area(tf.constant([
      [5.0, 3.0, 7.1],
      [2.3, 4.1, 4.8]
    ]))
  result = sess.run(area)
  print result

**Solution 4**

In [12]:
def compute_area(sides):
  # slice the input to get the sides
  a = sides[:,0]  # 5.0, 2.3
  b = sides[:,1]  # 3.0, 4.1
  c = sides[:,2]  # 7.1, 4.8
  
  # Heron's formula
  s = (a + b + c) * 0.5   # (a + b) is a short-cut to tf.add(a, b)
  areasq = s * (s - a) * (s - b) * (s - c) # (a * b) is a short-cut to tf.multiply(a, b), not tf.matmul(a, b)
  return tf.sqrt(areasq)

with tf.Session() as sess:
  # pass in two triangles
  area = compute_area(tf.constant([
      [5.0, 3.0, 7.1],
      [2.3, 4.1, 4.8]
    ]))
  result = sess.run(area)
  print result

[6.278497 4.709139]


## tf.eager

tf.eager allows you to avoid the build-then-run stages. However, most production code will follow the lazy evaluation paradigm because the lazy evaluation paradigm is what allows for multi-device support and distribution. 
<p>
One thing you could do is to develop using tf.eager and then comment out the eager execution and add in the session management code.

<b> You may need to click on Reset Session to try this out </b>

In [0]:
import tensorflow as tf
from tensorflow.contrib.eager.python import tfe
tfe.enable_eager_execution()

/Users/erwinh/anaconda/lib/python2.7/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [0]:
x = tf.constant([5, 3, 8])
y = tf.constant([3, -1, 2])
z = tf.add(x, y)
print z

tf.Tensor([ 8  2 10], shape=(3,), dtype=int32)


# If you have time left

## Layers 

Go and give the layers API a try. You can find more information on this page. [Tensorflow Layers](https://www.tensorflow.org/programmers_guide/low_level_intro#layers)



Copyright 2017 Google Inc. Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License